# See here for image contents: https://github.com/devcontainers/images/blob/main/src/python/README.md
ARG VARIANT="3.12"
FROM mcr.microsoft.com/devcontainers/python:${VARIANT}

# [Optional] If your requirements rarely change, uncomment this section to potentially speed up build times.
# COPY pyproject.toml poetry.lock* /tmp/
# RUN cd /tmp && pip install --upgrade pip && pip install poetry && poetry install --no-root

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

