name: Integration Tests

on:
  push:
    branches:
      - main
    paths:
      - 'destination-surrealdb/**'
      - '.devcontainer/**'
      - '.github/workflows/integration.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'destination-surrealdb/**'
      - '.devcontainer/**'
      - '.github/workflows/integration.yml'
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run integration tests in dev container
      uses: devcontainers/ci@v0.3
      with:
        workspaceFolder: /workspace/destination-surrealdb
        runCmd: |
          pwd
          ls -la
          poetry install --no-root
          poetry run python -m pytest integration_tests/integration_test.py -v -s --tb=long
        configFile: .devcontainer/devcontainer.json
        push: never
